name: outfit_maven
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2   # Use a stable version
  shared_preferences: ^2.2.1
  provider: ^6.1.2
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  firebase_storage: 12.4.1
  image_picker: ^1.0.7
  cloudinary_flutter: ^1.3.0
  cloudinary_public: 0.23.1
  fl_chart: ^0.40.0
  animate_do: ^4.2.0
  lottie: ^2.6.0 
  change_app_package_name: ^1.5.0
  uuid: ^3.0.7
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  open_filex: ^4.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/defaultprofile.png
    - assets/quiz_animation.json
    - assets/login_animation.json
    - assets/contact_us.json
    - assets/outfit_maven_logo.png
    - assets/manual.pdf
