name: outfit_maven
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2   # Use a stable version
  shared_preferences: ^2.2.1
  provider: ^6.1.2
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  firebase_storage: 12.4.1
  image_picker: ^1.0.7
  cloudinary_flutter: ^1.3.0
  cloudinary_public: 0.23.1
  fl_chart: ^0.40.0
  animate_do: ^4.2.0
  lottie: ^2.6.0 
  change_app_package_name: ^1.5.0
  uuid: ^3.0.7
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  open_filex: ^4.3.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/defaultprofile.png
    - assets/quiz_animation.json
    - assets/login_animation.json
    - assets/contact_us.json
    - assets/outfit_maven_logo.png
    - assets/quote.jpg
    - assets/manual.pdf
    - assets/quiz/
    - assets/quiz_results/
    - assets/quiz/weather_quiz.jpeg
    - assets/quiz/mood_quiz.jpeg
    - assets/quiz/occasion_quiz.jpeg
    - assets/quiz/accessories_quiz.jpeg
    - assets/quiz/todays_outfit_quiz.jpeg
    - assets/quiz_results/energetic_playful.jpeg
    - assets/quiz_results/calm_elegant.jpeg
    - assets/quiz_results/edgy_moody.jpeg
    - assets/quiz_results/cozy_minimal.jpeg
    - assets/quiz_results/casual_effortless.jpeg
    - assets/quiz_results/business_formal.jpeg
    - assets/quiz_results/elegant_bold.jpeg
    - assets/quiz_results/cozy_laidback.jpeg
    - assets/quiz_results/sunny_chic.jpeg
    - assets/quiz_results/rainy_cozy.jpeg
    - assets/quiz_results/winter_elegance.jpeg
    - assets/quiz_results/windy_casual.jpeg
    - assets/quiz_results/casual_comfy.jpeg
    - assets/quiz_results/chic_trendy.jpeg
    - assets/quiz_results/sporty_active.jpeg
    - assets/quiz_results/edgy_streetwear.jpeg
    - assets/quiz_results/minimal_elegant.jpeg
    - assets/quiz_results/bold_statement.jpeg
    - assets/quiz_results/sporty_functional.jpeg
    - assets/quiz_results/edgy_experimental.jpeg
